#! /bin/bash --posix

set -eux
set -o pipefail

# Grab site-specific variables for build environment.
. /etc/environment.build

readonly dir='/tmp/hypervisor-unpack'

rm -rf "$dir" || true
mkdir -p "$dir"
get-url "$dominator_components_directory/hypervisor.tar.gz" - |\
  tar -C "$dir" -xz

"$dir/install"
rm -rf "$dir"

mkdir /var/lib/hypervisor
