#! /bin/bash --posix

set -eux
set -o pipefail

# Grab site-specific variables for build environment.
. /etc/environment.build

dpkg -i /n/debian/main/pool/main/x/xview/olvwm_4.4.3.2p1.4-28.1_i386.deb
