#! /bin/bash --posix

set -eux
set -o pipefail

# Grab site-specific variables for build environment.
. /etc/environment.build

readonly dir='/tmp/imageserver-unpack'

useradd -r imageserver
rm -rf "$dir" || true
mkdir -p "$dir"
get-url "$dominator_components_directory/imageserver.tar.gz" - |\
  tar -C "$dir" -xz

"$dir/install"
rm -rf "$dir"

mkdir -p /var/log/imageserver
chown -R imageserver /etc/{,ssl/}imageserver /var/log/imageserver
systemctl enable imageserver
