#! /bin/bash --posix

set -eux
set -o pipefail

# Grab site-specific variables for build environment.
. /etc/environment.build

readonly dir='/tmp/dominator-unpack'

useradd -r dominator
rm -rf "$dir" || true
mkdir -p "$dir"
get-url "$dominator_components_directory/dominator.tar.gz" - |\
  tar -C "$dir" -xz

"$dir/install"
rm -rf "$dir"

mkdir -p /var/lib/Dominator /var/log/dominator
chown -R dominator /etc/{,ssl/}dominator /var/lib/Dominator /var/log/dominator
