#! /bin/bash --posix

set -eux
set -o pipefail

# Grab site-specific variables for build environment.
. /etc/environment.build

readonly dir='/tmp/filegen-server-unpack'

useradd -r filegen-server
rm -rf "$dir" || true
mkdir -p "$dir"
get-url "$dominator_components_directory/filegen-server.tar.gz" - |\
  tar -C "$dir" -xz

"$dir/install"
rm -rf "$dir"

mkdir -p /var/lib/filegen-server/computed-files/root /var/log/filegen-server
chown -R filegen-server /etc/ssl/filegen-server /var/{lib,log}/filegen-server
